### PR TITLE
Add support for scaling metrics before sending them

### PR DESCRIPTION
**Pull request by jeanmarc**
Using the same way kamon-statsd does this.
This PR implements Issue #2

### CODE REVIEW

**Comment by jeanmarc** [comment]
Please let me know if/when this pull request will be processed and a release is made available that incorporates it.

**Comment by dpsoft** [comment]
@jeanmarc looks good to me. @ivantopo WDYT?

**Comment by ivantopo** [comment]
LGTM too, could you please sign the CLA? 

https://docs.google.com/forms/d/e/1FAIpQLSdhLT5zYRzdzRKRybFJcXUUuhpdJzRiiDhPZKtCTgToQaqpGw/viewform

**Comment by jeanmarc** [comment]
Signed. Thanks for picking this up!

**Comment by ivantopo** [comment]
thanks a lot @jeanmarc! I just released this and another change I had related to retrying metrics as 1.1.0, soon this will be reflected in our website :)

**Pull request merged**
